steps:
# GITHUB KEY
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=gcloud/id_rsa_production.enc
  - --plaintext-file=/root/.ssh/id_rsa
  - --location=global
  - --keyring=infra
  - --key=github-key
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# GITHUB TO KNOWN_HOSTS
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod 600 /root/.ssh/id_rsa
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_rsa
    EOF
    mv gcloud/known_hosts /root/.ssh/known_hosts
    openssl req -new -newkey rsa:1024 -sha256 -days 7300 -nodes -x509 -subj "/CN=asiakas.test" -keyout nginx/environments/testing/http/default.key -out nginx/environments/testing/http/default.crt
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# COMPOSER
- name: 'composer'
  args: [ 'install', '--no-interaction' ]
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# PHPCS (uncomment if the tests should pass)
#- name: 'composer'
#  entrypoint: 'bash'
#  args:
#  - '-c'
#  - |
#    composer create-project wp-coding-standards/wpcs --no-dev /opt/wpcs
#    composer global require phpunit/phpunit
#    /opt/wpcs/vendor/bin/phpcs --config-set installed_paths /opt/wpcs
#    /opt/wpcs/vendor/bin/phpcs --extensions=php --standard=phpcs.xml --runtime-set ignore_warnings_on_exit true .

# WEBPACK
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    cd ./web/app/themes/THEMENAME
    npm install
    ./node_modules/webpack/bin/webpack.js

# INTEGRATION TESTS
- name: 'docker/compose:1.15.0'
  args: ['-f', 'docker-compose-gcloud.yml', 'run', 'web', '/bin/bash', '-c', './scripts/seed.sh; ./vendor/bin/codecept run --steps']

# BUILD AND PUSH IMAGE
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '--pull', '-t', 'gcr.io/$PROJECT_ID/PROJECTNAME:latest', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/PROJECTNAME:latest' ]

# UPGRADE KONTENA STACK
- name: 'kontena/cli'
  args: [ 'stack', 'upgrade', 'PROJECTNAME', 'kontena-production.yml' ]
  env: [ 'KONTENA_GRID=production' ]
  secretEnv: [ 'KONTENA_TOKEN', 'KONTENA_URL' ]

secrets:
- kmsKeyName: 'projects/geniem-production/locations/global/keyRings/infra/cryptoKeys/kontena-key'
  secretEnv:
    # encryted access token to kontena
    KONTENA_TOKEN: CiQArTuEBPB8p58oMikeTVwnuVkK9BM0Eflxaqc/k88ruNzG6YQSaQBs20RHsMS9ShQqi9J1KLmzl8CTruYVhLO1yqaouLozdGfPjXq0XfmIW2HdPg8s+3Dp7wTDLEFZ/gD0WoqdbEvp6G49P6OGeGgiDdKc3AGs5Qzb9VbyZatEorVhz6B0cKRCZ2Ro76Ob6Q==
    KONTENA_URL: CiQArTuEBMBfYArPS9M9VQbqDpKBMftThfpIw3mLTGaVWxeXSjESYwBs20RHSU7T02AW18ahXDtgGSMX4rmae5gdaiBJZtrsXL8Nw51aI4C3n4GFUnzsF/EZu6FoK1WdMw2IkEhIvkm6vV5+wZ76dM1Uw/n2EsjRrztGYURcLV4IOqAr9Un1Uv6NUA==
