steps:
# GITHUB KEY
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=gcloud/id_rsa_stage.enc
  - --plaintext-file=/root/.ssh/id_rsa
  - --location=global
  - --keyring=infra
  - --key=github-key
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# GITHUB TO KNOWN_HOSTS
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod 600 /root/.ssh/id_rsa
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_rsa
    EOF
    mv gcloud/known_hosts /root/.ssh/known_hosts
    openssl req -new -newkey rsa:1024 -sha256 -days 7300 -nodes -x509 -subj "/CN=tre3.test" -keyout nginx/environments/testing/http/default.key -out nginx/environments/testing/http/default.crt
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# COMPOSER
- name: 'composer'
  args: [ 'install', '--no-interaction' ]
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# PHPCS (uncomment if the tests should pass)
#- name: 'composer'
#  entrypoint: 'bash'
#  args:
#  - '-c'
#  - |
#    composer create-project wp-coding-standards/wpcs --no-dev /opt/wpcs
#    composer global require phpunit/phpunit
#    /opt/wpcs/vendor/bin/phpcs --config-set installed_paths /opt/wpcs
#    /opt/wpcs/vendor/bin/phpcs --extensions=php --standard=phpcs.xml --runtime-set ignore_warnings_on_exit true .

# WEBPACK
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    cd ./web/app/themes/THEMENAME
    npm install
    ./node_modules/webpack/bin/webpack.js

# INTEGRATION TESTS
- name: 'docker/compose:1.15.0'
  args: ['-f', 'docker-compose-gcloud.yml', 'run', 'web', '/bin/bash', '-c', './scripts/seed.sh; ./vendor/bin/codecept run --steps']

# BUILD AND PUSH IMAGE
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '--pull', '-t', 'gcr.io/$PROJECT_ID/PROJECTNAME:stage', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/PROJECTNAME:stage' ]

# UPGRADE KONTENA STACK
- name: 'kontena/cli'
  args: [ 'stack', 'upgrade', 'PROJECTNAME', 'kontena-stage.yml' ]
  env: [ 'KONTENA_GRID=stage' ]
  secretEnv: [ 'KONTENA_TOKEN', 'KONTENA_URL' ]

secrets:
- kmsKeyName: 'projects/geniem-stage/locations/global/keyRings/infra/cryptoKeys/kontena-key'
  secretEnv:
    # encryted access token to kontena
    KONTENA_TOKEN: CiQA4j4haRTCAuU1Klk0GBbPucq2JjVzH1CMMUH+WluMy5N93XkSaQDqV+JInB3iIVhb/6L1fuX4MNzyZehyotAHrYQZHqykjDW5kdM7ndH70WdnjhlPMuPUczlP1qQ7K2s5A1gaPXfQnqC1/ILiu2DO0w0WTrGfjzXabAMxNTEoX1Q252vU7PdSsvUmvziyzg==
    KONTENA_URL: CiQA4j4hadIFI1NAvNM+WY40MXjI7FdOggdDB3dxHMeZ3WP7tzMSYgDqV+JIAdwM0byeCb/Ss49OFlBokrZ3vi7Uk/irXeHw/kyGzs4i1CiBZgAoXEMPURMHPzzr0o/OZwwA+aplK4rCS+8oKzHYPoaKOv/trTjt97sQ2OAWur6PvPPHHA9LvLn6

